import { describe, expect, it } from "vitest";
import { isRuntimeFailSafePrompt } from "../app/lib/fail-safe-runtime-prompt.js";

describe("fail-safe-runtime-prompt", () => {
  it("detects runtime issue body markers", () => {
    const body = [
      "## Fail-Safe Runtime report",
      "Suggested agent branch: `cursor/runtime-fail-20260720-sidecar-offline`",
      "Generated by Fail-Safe Runtime (Product B).",
    ].join("\n");
    expect(isRuntimeFailSafePrompt(body)).toBe(true);
  });

  it("detects fail-safe-runtime title prefix", () => {
    expect(isRuntimeFailSafePrompt("[fail-safe-runtime] sidecar offline")).toBe(true);
  });

  it("ignores unrelated CI logs", () => {
    expect(isRuntimeFailSafePrompt("ci-gates — FAILED\neslint error")).toBe(false);
  });
});
