"use client";

import React, { useCallback, useEffect, useMemo } from "react";
import { AppHeader, SplashOverlay } from "./components/app-shell";
import { ActionToast } from "./components/action-toast";
import { useAnalyzers } from "./hooks/use-analyzers";
import { useClipboard } from "./hooks/use-clipboard";
import { useProjectActions } from "./hooks/use-project-actions";
import { useProjectPersistence } from "./hooks/use-project-persistence";
import { useProjectState } from "./hooks/use-project-state";
import { usePromptPipeline } from "./hooks/use-prompt-pipeline";
import { ProjectWorkspaceContext } from "./context/project-workspace-context";
import { PageSidebarLeft } from "./components/page-sidebar-left";
import { PageWorkspaceCenter } from "./components/page-workspace-center";
import { PageSidebarRight } from "./components/page-sidebar-right";
import { useSplashOverlay } from "./hooks/use-splash-seen";
import { useStatusMessage } from "./hooks/use-status-message";
import { useUndoSnapshot } from "./hooks/use-undo-snapshot";
import { APP_VERSION, AUTHOR } from "./lib/music-config";

export default function Page() {
  const { statusMessage: saveStatus, setStatusMessage, setStatusWithTime, toast, clearToast } = useStatusMessage("Not saved yet");
  const {
    patch,
    load: loadProjectState,
    resetBlank,
    idea,
    setIdea,
    tempo,
    setTempo,
    structure,
    setStructure,
    selectedGenres,
    setSelectedGenres,
    selectedRhythms,
    setSelectedRhythms,
    selectedSounds,
    setSelectedSounds,
    vocal,
    setVocal,
    mode,
    setMode,
    proMode,
    setProMode,
    promptIntensity,
    setPromptIntensity,
    variationCount,
    setVariationCount,
    rules,
    setRules,
    notes,
    setNotes,
    copied,
    setCopied,
    scores,
    setScores,
    mood,
    setMood,
    lyricTheme,
    setLyricTheme,
    lyricLanguage,
    setLyricLanguage,
    lyricStructure,
    setLyricStructure,
    lyricStyle,
    setLyricStyle,
    lyricDensity,
    setLyricDensity,
    promptFormat,
    setPromptFormat,
    promptEngine,
    setPromptEngine,
    coProducerOutput,
    setCoProducerOutput,
    generatedLyrics,
    setGeneratedLyrics,
    generatedLyricsStyle,
    setGeneratedLyricsStyle,
    generatedHooks,
    setGeneratedHooks,
    generatedHooksStyle,
    setGeneratedHooksStyle,
    lyricVariantSeed,
    setLyricVariantSeed,
    lyricsGenerateBusy,
    setLyricsGenerateBusy,
    coProducerLlmSettings,
    setCoProducerLlmSettings,
    lyricMode,
    setLyricMode,
    voiceRefFirstName,
    setVoiceRefFirstName,
    voiceRefLastName,
    setVoiceRefLastName,
    voiceStyleLine,
    setVoiceStyleLine,
    presetName,
    setPresetName,
    customPresets,
    setCustomPresets,
    history,
    setHistory,
    variations,
    setVariations,
    selectedHistoryId,
    setSelectedHistoryId,
    guidedStep,
    setGuidedStep,
    instrumentalVocalFx,
    setInstrumentalVocalFx,
  } = useProjectState();
  const { showSplash, dismissSplash, resetSplash } = useSplashOverlay();

  const applyAnalyzerPatch = useCallback((analyzerPatch) => {
    patch(analyzerPatch);
  }, [patch]);

  const {
    attachAudioFile,
    analyzeAudioFile,
    analyzeImageFile,
    applyAudioToSunoStyle,
    applyImageToSunoStyle,
    audioAnalysis,
    audioExportBusy,
    audioExportProgress,
    audioLoudness,
    audioLoudnessBusy,
    audioPreviewUrl,
    exportEnhancedAudio,
    canvasRef,
    clearAudioAnalysis,
    clearImageAnalysis,
    imageAnalysis,
    imagePreview,
    resetAnalyzers,
    setAudioAnalysis,
    setImageAnalysis,
    updateAudioAnalysis,
  } = useAnalyzers({
    promptEngine,
    setGuidedStep,
    applyAnalyzerPatch,
    setStatusWithTime,
  });

  const currentState = useMemo(
    () => ({
      appVersion: APP_VERSION,
      idea,
      tempo,
      structure,
      selectedGenres,
      selectedRhythms,
      selectedSounds,
      vocal,
      mode,
      proMode,
      promptIntensity,
      variationCount,
      rules,
      notes,
      scores,
      mood,
      audioAnalysis,
      imageAnalysis,
      lyricTheme,
      lyricLanguage,
      lyricStructure,
      lyricStyle,
      lyricDensity,
      promptFormat,
      promptEngine,
      coProducerOutput,
      generatedLyrics,
      generatedLyricsStyle,
      generatedHooks,
      generatedHooksStyle,
      lyricVariantSeed,
      lyricMode,
      voiceRefFirstName,
      voiceRefLastName,
      voiceStyleLine,
      instrumentalVocalFx,
      guidedStep,
      variations,
      history,
      selectedHistoryId,
    }),
    [
      idea,
      tempo,
      structure,
      selectedGenres,
      selectedRhythms,
      selectedSounds,
      vocal,
      mode,
      proMode,
      promptIntensity,
      variationCount,
      rules,
      notes,
      scores,
      mood,
      audioAnalysis,
      imageAnalysis,
      lyricTheme,
      lyricLanguage,
      lyricStructure,
      lyricStyle,
      lyricDensity,
      promptFormat,
      promptEngine,
      coProducerOutput,
      generatedLyrics,
      generatedLyricsStyle,
      generatedHooks,
      generatedHooksStyle,
      lyricVariantSeed,
      lyricMode,
      voiceRefFirstName,
      voiceRefLastName,
      voiceStyleLine,
      instrumentalVocalFx,
      guidedStep,
      variations,
      history,
      selectedHistoryId,
    ],
  );

  const loadState=useCallback((data)=>{
    loadProjectState(data);
    if (data.audioAnalysis) setAudioAnalysis(data.audioAnalysis);
    else clearAudioAnalysis();
    if (data.imageAnalysis) setImageAnalysis(data.imageAnalysis);
    else clearImageAnalysis();
  }, [clearAudioAnalysis, clearImageAnalysis, loadProjectState, setAudioAnalysis, setImageAnalysis]);

  const { captureSnapshot, revertSnapshot } = useUndoSnapshot(
    () => currentState,
    loadState,
    setStatusWithTime,
  );

  const { lastAutosavePayloadRef } = useProjectPersistence({
    currentState,
    loadState,
    patch,
    promptEngine,
    resetAnalyzers,
    setCustomPresets,
    setGuidedStep,
    setHistory,
    setStatusMessage,
    setStatusWithTime,
  });

  useEffect(() => {
    if (!showSplash) return;
    const timer = window.setTimeout(dismissSplash, 1800);
    const fallback = window.setTimeout(dismissSplash, 3500);
    window.addEventListener("pointerdown", dismissSplash, { once: true });
    window.addEventListener("keydown", dismissSplash, { once: true });
    return () => {
      window.clearTimeout(timer);
      window.clearTimeout(fallback);
      window.removeEventListener("pointerdown", dismissSplash);
      window.removeEventListener("keydown", dismissSplash);
    };
  }, [dismissSplash, showSplash]);

  const audioSummaryForPipeline = audioAnalysis?.summary ?? "";
  const imageSummaryForPipeline = imageAnalysis?.summary ?? "";
  const hasAudioAnalysis = Boolean(audioAnalysis);
  const hasImageAnalysis = Boolean(imageAnalysis);

  const pipelineAudioAnalysis = useMemo(
    () => (hasAudioAnalysis ? { summary: String(audioSummaryForPipeline) } : null),
    [hasAudioAnalysis, audioSummaryForPipeline],
  );

  const pipelineImageAnalysis = useMemo(
    () => (hasImageAnalysis ? { summary: String(imageSummaryForPipeline) } : null),
    [hasImageAnalysis, imageSummaryForPipeline],
  );

  const pipelineInput = useMemo(
    () => ({
      mood,
      promptIntensity,
      vocal,
      instrumentalVocalFx,
      lyricDensity,
      lyricLanguage,
      lyricTheme,
      lyricStyle,
      lyricMode,
      lyricStructure,
      selectedGenres,
      tempo,
      selectedSounds,
      selectedRhythms,
      idea,
      structure,
      rules,
      mode,
      promptFormat,
      promptEngine,
      coProducerOutput,
      notes,
      audioAnalysis: pipelineAudioAnalysis,
      imageAnalysis: pipelineImageAnalysis,
      voiceStyleLine,
      voiceRefFirstName,
      voiceRefLastName,
      generatedLyrics,
    }),
    [
      mood,
      promptIntensity,
      vocal,
      instrumentalVocalFx,
      lyricDensity,
      lyricLanguage,
      lyricTheme,
      lyricStyle,
      lyricMode,
      lyricStructure,
      selectedGenres,
      tempo,
      selectedSounds,
      selectedRhythms,
      idea,
      structure,
      rules,
      mode,
      promptFormat,
      promptEngine,
      coProducerOutput,
      notes,
      pipelineAudioAnalysis,
      pipelineImageAnalysis,
      voiceStyleLine,
      voiceRefFirstName,
      voiceRefLastName,
      generatedLyrics,
    ],
  );

  const {
    moodWords,
    intensityText,
    vocalText,
    lyricPrompt,
    prompt,
    sunoFieldSlices,
    sunoSlices,
    sunoWarnings,
    sunoGuidedInput,
    voiceStyleCompact,
    sourcePrompt,
  } = usePromptPipeline(pipelineInput);

  const avgScore = ((scores.bass + scores.rhythm + scores.identity + scores.clarity) / 4).toFixed(1);

  const { copyToClipboard } = useClipboard(setStatusWithTime);

  const {
    addHistory,
    addLyricsFromInstrumentalTrack,
    applyGenreAnchors,
    applyPreset,
    applyQuickFix,
    buildCoProducerAI,
    clearHistory,
    coProducer,
    copyPrompt,
    deleteCustomPreset,
    exportProject,
    fixSunoWarnings,
    generateExampleLyrics,
    generateHooks,
    generateVariations,
    generateVoiceStyleFromNames,
    importProject,
    loadPresetObject,
    resetAll,
    restoreHistory,
    saveCustomPreset,
    saveProject,
    shuffleExampleLyrics,
    toggle,
  } = useProjectActions({
    applyAudioToSunoStyle,
    audioAnalysis,
    avgScore,
    captureSnapshot,
    coProducerLlmSettings,
    copyToClipboard,
    currentState,
    customPresets,
    history,
    idea,
    imageAnalysis,
    instrumentalVocalFx,
    intensityText,
    lastAutosavePayloadRef,
    loadState,
    lyricDensity,
    lyricLanguage,
    lyricMode,
    lyricPrompt,
    lyricStructure,
    lyricStyle,
    lyricTheme,
    lyricVariantSeed,
    mode,
    mood,
    moodWords,
    patch,
    presetName,
    prompt,
    promptEngine,
    promptIntensity,
    resetAnalyzers,
    resetBlank,
    resetSplash,
    rules,
    scores,
    selectedGenres,
    selectedHistoryId,
    selectedRhythms,
    selectedSounds,
    setCopied,
    setCoProducerOutput,
    setCustomPresets,
    setGeneratedHooks,
    setGeneratedHooksStyle,
    setGeneratedLyrics,
    setGeneratedLyricsStyle,
    setGuidedStep,
    setHistory,
    setIdea,
    setInstrumentalVocalFx,
    setLyricMode,
    setLyricStructure,
    setLyricStyle,
    setLyricTheme,
    setLyricVariantSeed,
    setLyricsGenerateBusy,
    setMode,
    setMood,
    setNotes,
    setPresetName,
    setPromptEngine,
    setPromptIntensity,
    setRules,
    setSelectedGenres,
    setSelectedHistoryId,
    setSelectedRhythms,
    setSelectedSounds,
    setStatusWithTime,
    setStructure,
    setTempo,
    setVariationCount,
    setVariations,
    setVocal,
    setVoiceRefFirstName,
    setVoiceRefLastName,
    setVoiceStyleLine,
    structure,
    tempo,
    variationCount,
    vocal,
    vocalText,
    voiceRefFirstName,
    voiceRefLastName,
  });
  const workspace = useMemo(
    () => ({
    addHistory,
    addLyricsFromInstrumentalTrack,
    analyzeAudioFile,
    analyzeImageFile,
    applyAudioToSunoStyle,
    applyGenreAnchors,
    applyImageToSunoStyle,
    applyPreset,
    applyQuickFix,
    attachAudioFile,
    audioAnalysis,
    audioExportBusy,
    audioExportProgress,
    audioLoudness,
    audioLoudnessBusy,
    audioPreviewUrl,
    buildCoProducerAI,
    clearAudioAnalysis,
    clearHistory,
    clearImageAnalysis,
    captureSnapshot,
    coProducer,
    coProducerLlmSettings,
    coProducerOutput,
    copied,
    copyPrompt,
    copyToClipboard,
    customPresets,
    deleteCustomPreset,
    exportEnhancedAudio,
    exportProject,
    fixSunoWarnings,
    generateExampleLyrics,
    generateHooks,
    generateVariations,
    generateVoiceStyleFromNames,
    generatedHooks,
    generatedHooksStyle,
    generatedLyrics,
    generatedLyricsStyle,
    guidedStep,
    history,
    idea,
    imageAnalysis,
    imagePreview,
    importProject,
    instrumentalVocalFx,
    intensityText,
    loadPresetObject,
    lyricDensity,
    lyricLanguage,
    lyricMode,
    lyricPrompt,
    lyricStructure,
    lyricStyle,
    lyricTheme,
    lyricsGenerateBusy,
    mode,
    mood,
    notes,
    presetName,
    proMode,
    prompt,
    promptEngine,
    promptFormat,
    promptIntensity,
    resetAll,
    restoreHistory,
    revertSnapshot,
    rules,
    saveCustomPreset,
    saveProject,
    scores,
    selectedGenres,
    selectedHistoryId,
    selectedRhythms,
    selectedSounds,
    setCoProducerLlmSettings,
    setCoProducerOutput,
    setCopied,
    setGeneratedLyrics,
    setGuidedStep,
    setIdea,
    setInstrumentalVocalFx,
    setLyricDensity,
    setLyricLanguage,
    setLyricMode,
    setLyricStructure,
    setLyricStyle,
    setLyricTheme,
    setMode,
    setMood,
    setNotes,
    setPresetName,
    setProMode,
    setPromptEngine,
    setPromptFormat,
    setPromptIntensity,
    setRules,
    setScores,
    setSelectedGenres,
    setSelectedRhythms,
    setSelectedSounds,
    setStatusWithTime,
    setStructure,
    setTempo,
    setVariationCount,
    setVoiceRefFirstName,
    setVoiceRefLastName,
    setVoiceStyleLine,
    setVocal,
    shuffleExampleLyrics,
    sourcePrompt,
    structure,
    sunoFieldSlices,
    sunoGuidedInput,
    sunoSlices,
    sunoWarnings,
    tempo,
    toggle,
    updateAudioAnalysis,
    variationCount,
    variations,
    vocal,
    voiceRefFirstName,
    voiceRefLastName,
    voiceStyleCompact,
    voiceStyleLine,
  }),
  [
    addHistory,
    addLyricsFromInstrumentalTrack,
    analyzeAudioFile,
    analyzeImageFile,
    applyAudioToSunoStyle,
    applyGenreAnchors,
    applyImageToSunoStyle,
    applyPreset,
    applyQuickFix,
    attachAudioFile,
    audioAnalysis,
    audioExportBusy,
    audioExportProgress,
    audioLoudness,
    audioLoudnessBusy,
    audioPreviewUrl,
    buildCoProducerAI,
    captureSnapshot,
    clearAudioAnalysis,
    clearHistory,
    clearImageAnalysis,
    coProducer,
    coProducerLlmSettings,
    coProducerOutput,
    copied,
    copyPrompt,
    copyToClipboard,
    customPresets,
    deleteCustomPreset,
    exportEnhancedAudio,
    exportProject,
    fixSunoWarnings,
    generateExampleLyrics,
    generateHooks,
    generateVariations,
    generateVoiceStyleFromNames,
    generatedHooks,
    generatedHooksStyle,
    generatedLyrics,
    generatedLyricsStyle,
    guidedStep,
    history,
    idea,
    imageAnalysis,
    imagePreview,
    importProject,
    instrumentalVocalFx,
    intensityText,
    loadPresetObject,
    lyricDensity,
    lyricLanguage,
    lyricMode,
    lyricPrompt,
    lyricStructure,
    lyricStyle,
    lyricTheme,
    lyricsGenerateBusy,
    mode,
    mood,
    notes,
    presetName,
    proMode,
    prompt,
    promptEngine,
    promptFormat,
    promptIntensity,
    resetAll,
    restoreHistory,
    revertSnapshot,
    rules,
    saveCustomPreset,
    saveProject,
    scores,
    selectedGenres,
    selectedHistoryId,
    selectedRhythms,
    selectedSounds,
    setCoProducerLlmSettings,
    setCoProducerOutput,
    setCopied,
    setGeneratedLyrics,
    setGuidedStep,
    setIdea,
    setInstrumentalVocalFx,
    setLyricDensity,
    setLyricLanguage,
    setLyricMode,
    setLyricStructure,
    setLyricStyle,
    setLyricTheme,
    setMode,
    setMood,
    setNotes,
    setPresetName,
    setProMode,
    setPromptEngine,
    setPromptFormat,
    setPromptIntensity,
    setRules,
    setScores,
    setSelectedGenres,
    setSelectedRhythms,
    setSelectedSounds,
    setStatusWithTime,
    setStructure,
    setTempo,
    setVariationCount,
    setVoiceRefFirstName,
    setVoiceRefLastName,
    setVoiceStyleLine,
    setVocal,
    shuffleExampleLyrics,
    sourcePrompt,
    structure,
    sunoFieldSlices,
    sunoGuidedInput,
    sunoSlices,
    sunoWarnings,
    tempo,
    toggle,
    updateAudioAnalysis,
    variationCount,
    variations,
    vocal,
    voiceRefFirstName,
    voiceRefLastName,
    voiceStyleCompact,
    voiceStyleLine,
  ],
  );

  return (
    <main className="min-h-screen overflow-hidden bg-[#0b0d10] p-4 text-white md:p-8">
      {showSplash && (
        <SplashOverlay
          onDismiss={() => {
            dismissSplash();
            setStatusWithTime("Ready — build your prompt step by step", "info");
          }}
        />
      )}

      <ActionToast toast={toast} onDismiss={clearToast} />

      <canvas ref={canvasRef} className="hidden"/>
      <div className="fixed inset-0 pointer-events-none opacity-40" style={{background:"radial-gradient(circle at 18% 0%, rgba(184,115,51,.25), transparent 34%), radial-gradient(circle at 82% 12%, rgba(34,211,238,.16), transparent 36%), linear-gradient(135deg, rgba(255,255,255,.05), transparent 35%)"}}/>
      <div className="relative mx-auto max-w-7xl pb-12">
        <AppHeader
          appVersion={APP_VERSION}
          avgScore={avgScore}
          saveStatus={saveStatus}
          statusPulseKey={toast?.tick ?? 0}
        />

        <ProjectWorkspaceContext.Provider value={workspace}>
          <div className="grid gap-4 lg:grid-cols-[300px_1fr_380px]">
            <PageSidebarLeft />
            <PageWorkspaceCenter />
            <PageSidebarRight />
          </div>
        </ProjectWorkspaceContext.Provider>

      </div>
      <div className="fixed bottom-3 left-6 z-50 rounded-full border border-orange-400/30 bg-black/50 px-3 py-1 text-xs font-bold text-orange-300 backdrop-blur">Version {APP_VERSION}</div>
      <div className="fixed bottom-3 right-6 z-50 rounded-full border border-white/10 bg-black/50 px-3 py-1 text-xs text-white/60 backdrop-blur">Created by <span className="font-bold text-orange-300">{AUTHOR}</span></div>
    </main>
  );
}
